### ISSUE TITLE
Feature: Setup Routing

### ISSUE THREAD

**Issue by lloyddayekh** [moedayraki/lebaneselw-frontend#5]
Setup dynamic routing

- [x] Check path in State Object
- [x] Generate dynamic route based on path variable

**Comment by moedayraki** [comment]
With the new updates, all the routes are considered categories now. This will make the Category.vue the default view and other views won't be used.

As discussed before, there should be 5 views other than the Category & Item views. 

![Screen Shot 2022-03-02 at 9 38 53 PM](https://user-images.githubusercontent.com/54773679/156486011-895eab69-e3f8-4926-ae19-167c6ba992b0.png)
.
